apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: skatepark-api-go-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skatepark-api-go-deployment
    spec:
      containers:
      - name: skatepark-api-go
        image: us.gcr.io/%GCLOUD_PROJECT_ID%/skatepark-api-go:%GIT_COMMIT_SHA%
        env:
        - name: IMGUR_API_KEY
          valueFrom:
            secretKeyRef:
              name: skateparks-secrets
              key: imgurAPIKey
        - name: SKATEPARKS_FILE
          value: "./repository/json/"
        ports:
        - containerPort: 8080
          name: api
        livenessProbe:
          httpGet:
            path: /alive
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
             path: /ready
             port: 8080
          initialDelaySeconds: 30
        resources:
          limits:
            cpu: "50m"
            memory: "50Mi"
          requests:
            cpu: "10m"
            memory: "10Mi"