apiVersion: v1
kind: Service
metadata:
  labels:
    app: skatepark-api-go-deployment
  name: skatepark-api-go-service
  namespace: default
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: swagger
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: skatepark-api-go-deployment
  type: ClusterIP